"""Security test generation from scan findings (WSTG v4.2 input-validation
chapters + NIST SP 800-115 + OWASP Code Review Guide).

Given a scan's findings and the entry points the crawler discovered (query
params + form fields), this module emits concrete, reproducible test artifacts:

  * a raw HTTP request template with Burp Intruder positional markers (\u00a7)
  * payload wordlists per class (SQLi, XSS, path traversal, blind SQLi)
  * a stdlib-only Python fuzzer that replays the payloads against the target
  * a bash/curl command set

SAFETY: every payload is read-only/benign (the same probes the engine uses),
and generated tests are documented to run ONLY against targets you own or are
authorized to scan. The fuzzer is advisory output, not an exploit.
"""
from __future__ import annotations
import json
import urllib.parse
from datetime import datetime

from websec_auditor import config


# Category -> (payload list, source_id, label). All payloads are read-only and
# mirror the engine's probes so results stay consistent with the report.
_PAYLOAD_SOURCES = {
    "sqli": (["'", "' OR '1'='1", "' OR '1'='1-- "],
             "WSTG-INPV-05-SQLI", "SQL injection"),
    "xss": (["<websec_xss_probe_9f6b2>", "\"><websec_xss_probe_9f6b2>"],
            "WSTG-INPV-01-XSS", "Cross-site scripting"),
    "traversal": (config.PATH_TRAVERSAL_PAYLOADS,
                  "WSTG-INPV-07-PATHTRAV", "Path traversal / LFI"),
    "blindsqli": (config.BLIND_SQLI_TIMING_PAYLOADS + ["' AND '1'='1", "' AND '1'='2"],
                  "WSTG-INPV-05-SQLI", "Blind SQL injection"),
    "ratelimit": (["probe-1", "probe-2", "probe-3", "probe-4", "probe-5"],
                  "OWASP-RATELIMIT-BRUTEFORCE", "Rate limiting / brute-force"),
    "csrf": ([], "WSTG-SESS-05-CSRF", "Cross-Site Request Forgery"),
}


def _categories_from(findings):
    cats = set()
    for f in findings or []:
        d = f.to_dict() if hasattr(f, "to_dict") else f
        cwe = d.get("cwe", "") or ""
        check = (d.get("check", "") or "").lower()
        if cwe == "CWE-89":
            cats.add("sqli")
        if cwe == "CWE-79":
            cats.add("xss")
        if cwe in ("CWE-22", "CWE-98"):
            cats.add("traversal")
        if check in ("blind_sqli", "blind-sqli") or "blind" in check:
            cats.add("blindsqli")
        if "rate_limit" in check:
            cats.add("ratelimit")
        if cwe == "CWE-352" or check == "csrf":
            cats.add("csrf")
    return cats


def _collect_params(raw):
    """Pull entry points (query params + form fields) out of a crawl record."""
    params = []
    for page in (raw or {}).get("pages", []):
        params.extend(page.get("params") or [])
        for form in page.get("forms") or []:
            params.extend(form.get("fields") or [])
    seen = []
    for p in params:
        if p and p not in seen:
            seen.append(p)
    return seen or ["q"]


def _burp_request(target, params):
    parsed = urllib.parse.urlsplit(target)
    path = parsed.path or "/"
    base = parsed.query
    for p in params:
        if p not in base:
            base = base + ("&" if base else "") + f"{p}=x"
    marked = []
    for pair in base.split("&"):
        if "=" in pair:
            k, v = pair.split("=", 1)
            marked.append(f"{k}=\u00a7{v}\u00a7")
        else:
            marked.append(pair)
    host = parsed.netloc
    return (f"GET {path}?{'&'.join(marked)} HTTP/1.1\r\n"
            f"Host: {host}\r\n"
            "User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/120.0.0.0 Safari/537.36 websec-auditor-test/1.0\r\n"
            "Accept: text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8\r\n"
            "Connection: close\r\n\r\n")


def _fuzzer_py(target, params, cats):
    payloads = {}
    signatures = {"sqli": config.SQL_ERROR_SIGNATURES[:5],
                  "traversal": config.PATH_TRAVERSAL_SIGNATURES}
    for c in cats:
        plist = _PAYLOAD_SOURCES[c][0]
        if plist:
            payloads[c] = plist
    json_payloads = json.dumps(payloads)
    json_sig = json.dumps(signatures)
    script = f'''"""websec_fuzzer.py - generated by websec-auditor testgen
Target : {target}
Params : {", ".join(params)}
Classes: {", ".join(sorted(cats)) or "none"}
Generated : {datetime.now().isoformat(timespec="seconds")}

Stdlib-only, READ-ONLY fuzzer. Replays the benign probe payloads from the
associated audit report and prints how the app reacts. Run ONLY against
targets you own or are authorized to test.

Usage:
    python websec_fuzzer.py --url "{target}" --param {params[0] if params else "q"} --type {sorted(cats)[0] if cats else "sqli"} [--timeout 3]
"""
import argparse
import sys
import urllib.parse
import urllib.request

PAYLOADS = {json_payloads}
SIGNATURES = {json_sig}

def probe(url):
    req = urllib.request.Request(url, headers={{
        "User-Agent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/120.0.0.0 Safari/537.36 websec-auditor-test/1.0",
    }})
    # Verified TLS by default (no relaxed context): the generated fuzzer must
    # not silently accept a MiTM. Run only against owned/authorized targets.
    with urllib.request.urlopen(req, timeout=ARGS.timeout) as r:  # codereview-ignore: urlopen-user-input (standalone generated template; operator-supplied --url)
        return r.status, r.read(200000).decode("utf-8", "ignore")

def main():
    if not ARGS.url or ARGS.url in ("URL_HERE", ""):
        print("Provide --url (the target you own/authorized).")
        sys.exit(2)
    base = ARGS.url if ARGS.url.startswith("http") else "https://" + ARGS.url
    kind = ARGS.type
    if kind not in PAYLOADS:
        print(f"No payloads for type {{kind!r}}; choose from: {{', '.join(sorted(PAYLOADS))}}")
        sys.exit(2)
    print(f"Fuzzing {{kind}} against {{base}} (read-only probes)")
    for i, payload in enumerate(PAYLOADS[kind]):
        sep = "&" if "?" in base else "?"
        url = base + sep + urllib.parse.urlencode({{ARGS.param: payload}})
        try:
            status, body = probe(url)
        except Exception as e:
            print(f"[{{i+1:>2}}] ERROR  {{payload!r:<40}} -> {{e}}")
            continue
        hits = [sig for sig in SIGNATURES.get(kind, []) if sig.lower() in body.lower()]
        echoed = payload.lower() in body.lower()
        tag = "ECHOED" if echoed else ("SIGNAL " + ", ".join(hits) if hits else "ok")
        print(f"[{{i+1:>2}}] {{status:<5}} {{payload!r:<40}} -> {{tag}}")

if __name__ == "__main__":
    ARGS = None
    p = argparse.ArgumentParser()
    p.add_argument("--url", default="URL_HERE")
    p.add_argument("--param", default="{params[0] if params else "q"}")
    p.add_argument("--type", default="{sorted(cats)[0] if cats else "sqli"}")
    p.add_argument("--timeout", type=float, default=3.0)
    ARGS = p.parse_args()
    main()
'''
    return script


def _curl_sh(target, params, cats):
    lines = ["#!/usr/bin/env bash",
             "# Generated by websec-auditor testgen - READ-ONLY probes.",
             "# Run ONLY against targets you own / are authorized to test.",
             f"TARGET=\"{target}\"",
             ""]
    for c in sorted(cats):
        label, payloads = _PAYLOAD_SOURCES[c][1], _PAYLOAD_SOURCES[c][0]
        sep = "&" if "?" in target else "?"
        for p in params:
            for payload in payloads[:3]:
                enc = urllib.parse.quote(payload)
                lines.append(f"# {label} -> {p}")
                lines.append('curl -s -o /dev/null -w \'%{http_code} %{size_download}\\n\' '
                             '"$TARGET' + sep + p + "=" + enc + '"')
    return "\n".join(lines)


def _test_plan(enriched, target, cats, params):
    parts = [f"# Security Test Plan - {target}",
             f"Generated: {datetime.now().isoformat(timespec='seconds')}",
             f"Entry points: {', '.join(params)}",
             f"Classes to test: {', '.join(sorted(cats)) or 'none'}",
             ""]
    if enriched:
        parts.append("## Grounding: findings that triggered these tests")
        for e in enriched:
            f = e.get("finding", {})
            cits = e.get("citations") or []
            parts.append(f"- [{f.get('severity', 'info').upper()}] {f.get('name')} ({f.get('cwe')}/{f.get('owasp')})")
            for c in cits[:1]:
                parts.append(f"  - {c.get('title')} ({c.get('authority')}) {c.get('url')}")
        parts.append("")
    parts.append("## Run order")
    parts.append("1. Burp: import the raw request template, set Intruder payload "
                 "positions (already marked with \\u00a7), load the matching wordlist.")
    parts.append("2. CLI fuzzer: python websec_fuzzer.py --url <url> --param <p> --type <class>")
    parts.append("3. Confirm each reproduction manually; a finding is only real if "
                 "the echo/signature is observed and the impact is verified.")
    return "\n".join(parts)


def generate(target, params=None, findings=None, enriched=None):
    """Return a dict of test artifacts:
    {target, categories, params, burp_request, payloads, fuzz_py, curl_sh, plan}."""
    raw = {}
    if getattr(findings, "raw", None):
        raw = findings.raw
    if findings is not None and not isinstance(findings, (list, tuple)):
        findings = getattr(findings, "findings", None) or []
    cats = _categories_from(findings)
    params = params or _collect_params(raw)
    payloads = {c: _PAYLOAD_SOURCES[c][0] for c in sorted(cats)
                if _PAYLOAD_SOURCES[c][0]}
    return {
        "target": target,
        "categories": sorted(cats),
        "params": params,
        "burp_request": _burp_request(target, params),
        "payloads": payloads,
        "fuzz_py": _fuzzer_py(target, params, cats),
        "curl_sh": _curl_sh(target, params, cats),
        "plan": _test_plan(enriched, target, cats, params),
    }


def bundle_text(artifacts):
    """Flatten all artifacts into one text file (for the web UI download)."""
    parts = []
    parts.append("=" * 70)
    parts.append(f"WEBSEC-AUDITOR TEST PACKAGE - {artifacts['target']}")
    parts.append(f"Generated: {datetime.now().isoformat(timespec='seconds')}")
    parts.append(f"Categories: {', '.join(artifacts['categories']) or 'none'}")
    parts.append("=" * 70)
    parts.append("\n# 1. TEST PLAN\n")
    parts.append(artifacts["plan"])
    parts.append("\n" + "=" * 70 + "\n# 2. BURP INTRUDER RAW REQUEST (positions marked with \\u00a7)\n")
    parts.append(artifacts["burp_request"])
    for cat in sorted(artifacts["payloads"]):
        parts.append("\n" + "=" * 70)
        parts.append(f"# 3. PAYLOAD WORDLIST - {cat.upper()} (paste into Burp Intruder payloads)")
        parts.append("=" * 70)
        parts.append("\n".join(artifacts["payloads"][cat]))
    parts.append("\n" + "=" * 70 + "\n# 4. PYTHON FUZZER (read-only, stdlib only)\n")
    parts.append(artifacts["fuzz_py"])
    parts.append("\n" + "=" * 70 + "\n# 5. CURL COMMAND SET\n")
    parts.append(artifacts["curl_sh"])
    parts.append("\n" + "=" * 70 + "\nEND OF PACKAGE\n")
    return "\n".join(parts)
